### ISSUE TITLE
Memory Leak Problem

### ISSUE THREAD

**Issue by zhjjj** [mymonero/mymonero-core-js#8] opened 2018-04-17 13:19 UTC
We found a memory leak problem after our service with this lib running a while. The error log says:

**Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 16777216, (2) compile with ALLOW_MEMORY_GROWTH which adjusts the size at runtime but prevents some optimizations, or (3) set Module.TOTAL_MEMORY before the program runs.**

Then I notice that the leak is from [cryptonote_crypto_EMSCRIPTEN.js](https://github.com/mymonero/mymonero-core-js/blob/master/cryptonote_utils/cryptonote_crypto_EMSCRIPTEN.js)  __malloc_  because  __free_ is not implemented. 
The [emscripten](https://github.com/mymonero/mymonero-core-js/blob/master/cryptonote_utils/cryptonote_crypto_EMSCRIPTEN.js) does not implement _free_ method  and some explanation can be found [here](https://github.com/kripken/emscripten/issues/2621)

It is a very serious problem but I can do nothing about it.  So can you fix this thing or give me some advice pls? 

Thanks!

**Comment by paulshapiro** [comment] 2018-04-17 15:37
Hi zhjjj,

First I am hearing of it. Good find... it's a shame you're experiencing this issue.

That file represents a slightly hand-modified version (see env detection in header.. the Cordova lines can be removed now as we are going native Android) of an emscripten-built package (which I renamed to cryptonote_crypto_EMSCRIPTEN.js) which has, in fact, not been rebuilt in a relatively long time since the MyMonero web wallet was first put together. One pro of that is it's been stable in our tests and has had its behavior well tested by users.

There may have been a significant change in emscripten in the intervening time which, if a recent version of emscripten were used it could remove the need to determine and locate the same emscripten version as was used originally and rebuild the original C++ cryptonote code (which we do have).

I have my hands full right now but I wanted to comment and let you know that we will have someone joining our team soon to maintain and grow this repo, mymonero-core-js, so if I don't get to this, that person will follow up. If all goes to plan, this library will eventually be backed by a Monero mainline libcommon (containing basically cryptonote) along with our own C/C++ with some shared functions to reproduce the same API - which will be able to be trivially transpiled - but that's going to take some time as we are the only ones working on it to my knowledge at this moment.

Thanks,

**Comment by paulshapiro** [comment] 2018-04-17 15:38
P.S. thanks for the background info

**Comment by zhjjj** [comment] 2018-04-18 03:13
OK, glad to hear that and I will be waiting for your update!

**Comment by ReZarrected** [comment] 2018-07-23 23:13
What's the status of this issue? Has it been resolved yet? Is there anything I can do to help, I'm also experiencing the same memory issue.

**Comment by paulshapiro** [comment] 2018-07-23 23:17
I've actually made a ton of headway on this (see the cpp branch as well as the repo in progress, mymonero-core-cpp--new). The only thing I'm waiting on pertaining to this issue is on cpp, we are looking at a fix to emscripten behavior in locating its wasm file at runtime due to environment detection (https://github.com/kripken/emscripten/issues/6889, https://github.com/kripken/emscripten/issues/6871, https://github.com/kripken/emscripten/pull/5368). The fix for now may end up being to patch it by custom `--pre-js`. I'm porting `create_transaction` and will circle back to the emscripten rebuild once that's wrapped up so we can knock it out in one shot.

**Comment by paulshapiro** [comment] 2018-07-29 18:30
So just fyi it turns out that I completely missed a way the code provides to pass options in. Looking to have this reading soonish.

**Comment by paulshapiro** [comment] 2018-08-29 22:01
Hi, @zhjjj , @ReZarrected , can you check https://github.com/mymonero/mymonero-core-js/pull/41 on the `cpp` branch and let me know if this issue still exists? There are options in emscripten compilation for allowing memory growth, etc.

**Comment by paulshapiro** [comment] 2018-10-30 21:42
The new emscripten build provides considerably improved control over memory behavior and we've seen that memory growth works with wasm (but is not compatible with an asmjs build anyway). Closing this.

**Comment by paulshapiro** [comment] 2018-10-30 22:40
Actually, there may be a way to enable memory growth. Depends on performance.

**Comment by paulshapiro** [comment] 2019-03-26 16:45
Most browsers support WASM, so I'm going to close this provisionally as it's functionally fixed.

**Closed by paulshapiro** 2019-03-26 16:45 UTC
Labels: high priority
